### ISSUE TITLE
NPE on YouTubeExtractor.extract(videoId)

### ISSUE THREAD

**Issue by e16din** [Commit451/YouTubeExtractor#14]
version: 4.0.0
videoId: "UAz1Apj2kqs"
exception:
```
kotlin.KotlinNullPointerException
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:79)
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:16)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:2801)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by Jawnnypoo** [comment]
Just got a chance to test this out, and it extracts just fine for me. Are you sure this is still happening and that you are on version 4.0.0 of the library?

**Comment by e16din** [comment]
I am on version 4.0.0 of the library.
And, I used the library from Java project, may be this is a reason.

**Comment by Jawnnypoo** [comment]
Can you maybe post a snippet of what your code looks like?
