### ISSUE TITLE
 kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by captain-nemo1** [Commit451/YouTubeExtractor#46]
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | kotlin.KotlinNullPointerException
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
        at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.Single.subscribe(Single.java:3652)
        at io.reactivex.Single.subscribe(Single.java:3620)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: kotlin.KotlinNullPointerException
        at com.commit451.youtubeextractor.YouTubeExtractor.parseItag(YouTubeExtractor.kt:194)
        at com.commit451.youtubeextractor.YouTubeExtractor.parseItags(YouTubeExtractor.kt:176)
        at com.commit451.youtubeextractor.YouTubeExtractor.parseStreams(YouTubeExtractor.kt:158)
        at com.commit451.youtubeextractor.YouTubeExtractor.access$parseStreams(YouTubeExtractor.kt:15)
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:79)
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:15)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.Single.subscribe(Single.java:3652) 
        at io.reactivex.Single.subscribe(Single.java:3620)
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by Jawnnypoo** [comment]
What is the YouTube video ID?

**Comment by captain-nemo1** [comment]
Happening in all that I tried with.

**Comment by captain-nemo1** [comment]
https://www.youtube.com/watch?v=OgCVBmIlIro
Here man

**Comment by denizzk** [comment]
The reason of this issue is they changed the json name of the `cipher` to `signatureCipher`. But besides that there are other differences on the response too. I made a [PR](https://github.com/Commit451/YouTubeExtractor/pull/51) that fixes this issue.

**Comment by Jawnnypoo** [comment]
Thanks, released as 6.0.1
