### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by tolgahanalb** [Commit451/YouTubeExtractor#47]
java.lang.NumberFormatException: For input string: ""
        at java.lang.Long.parseLong(Long.java:606)
        at java.lang.Long.parseLong(Long.java:636)
        at com.commit451.youtubeextractor.YouTubeExtractor.viewCountFromHtml(YouTubeExtractor.kt:121)
        at com.commit451.youtubeextractor.YouTubeExtractor.access$viewCountFromHtml(YouTubeExtractor.kt:15)
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:87)
        at com.commit451.youtubeextractor.YouTubeExtractor$extract$1.call(YouTubeExtractor.kt:15)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by thaithcock** [comment]
Hi, I'm also running into this, but it seems to be intermittent. This seems to happen when Youtube returns a strange mostly empty page. I dug in and found that the stream URLs are still there, so I'm thinking we can just ignore exceptions unrelated to getting the URLs.
